import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')

describe('Contributions canonical source contract', () => {
  test('financial Contributions remain separate from GuestContribution', () => {
    const migration = read('prisma/migrations/20260819033000_contributions_resource_accounting/migration.sql')
    expect(migration).toContain('CREATE SCHEMA IF NOT EXISTS wewed_contributions')
    expect(migration).toContain('wedding_contributions')
    expect(migration).not.toContain('ALTER TABLE public."GuestContribution"')
  })

  test('direct vendor payments remain EngagementPayment facts', () => {
    const route = read('src/app/api/planner/contributions/route.ts')
    expect(route).toContain('tx.engagementPayment.create')
    expect(route).toContain("'CONTRIBUTION'")
    expect(route).toContain('alreadyIncludedInBudgetPaid')
    expect(route).toContain('PAYMENT_MATCH_AMBIGUOUS')
    expect(route).toContain('existingFundingRows')
  })

  test('legacy paid amount is never silently classified as couple-funded', () => {
    const budget = read('src/app/api/planner/budget/route.ts')
    expect(budget).toContain('legacyUnattributed')
    expect(budget).toContain('item.paidAmount - attributed')
    expect(budget).not.toContain("sourceKind: 'COUPLE', amount: item.paidAmount")
  })

  test('historical paid attribution cannot reuse the same contribution cash twice', () => {
    const funding = read('src/app/api/planner/budget/funding/route.ts')
    expect(funding).toContain('contributionAvailableAmount')
    expect(funding).toContain('contributionAllocatedCash')
    expect(funding).toContain('reservedRemaining')
    expect(funding).toContain('additionalReservation')
    expect(funding).toContain('CONTRIBUTION_INSUFFICIENT_AVAILABLE')
    expect(funding).toContain('pg_advisory_xact_lock')
  })

  test('Planner UI is responsive and uses plain language', () => {
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(ui).toContain('Record the help, not accounting jargon')
    expect(ui).toContain('md:hidden')
    expect(ui).toContain('hidden overflow-x-auto md:block')
    expect(ui).toContain('source not recorded')
  })

  test('Contributions is a canonical and visible Planner module', () => {
    const routeState = read('src/lib/planner-route-state.ts')
    const workspace = read('src/components/wedding/planner-workspace.tsx')
    const stage7 = read('src/components/wedding/planner-workspace-stage7.tsx')
    const page = read('src/app/planner/contributions/page.tsx')
    expect(routeState).toContain("| 'contributions'")
    expect(workspace).toContain("value: 'contributions', label: 'Contributions'")
    expect(workspace).toContain("activeTab === 'contributions'")
    expect(workspace).toContain('planner-contributions-overview')
    expect(stage7).toContain("{ value: 'contributions', label: 'Contributions', worksheetKey: 'contributions' }")
    expect(stage7).not.toContain("router.push('/planner/contributions')")
    expect(page).toContain('SecureWeddingPlanner')
  })

  test('Contributions has an executable desktop and mobile browser reachability contract', () => {
    const browser = read('tests/e2e/planner-contributions.spec.ts')
    expect(browser).toContain('Planner workspace sections')
    expect(browser).toContain('Planner workspace section')
    expect(browser).toContain('@mobile')
    expect(browser).toContain('/planner/contributions')
  })

  test('Notebook links use the existing entity-link action', () => {
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(ui).toContain("action: 'add-link'")
    expect(ui).toContain("entityType: 'WeddingContribution'")
  })

  test('Contributor capture exposes the private entity fields supported by the schema', () => {
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    const route = read('src/app/api/planner/contributions/route.ts')
    expect(ui).toContain('Contributor type')
    expect(ui).toContain('Preferred contributor contact')
    expect(ui).toContain('publicRecognition')
    expect(route).toContain('preferred_contact_method')
    expect(route).toContain('public_recognition')
    expect(route).toContain('address')
  })

  test('Campaign creation supports governed wedding-support categories instead of honeymoon-only data', () => {
    const domain = read('src/lib/contributions.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    const route = read('src/app/api/planner/contribution-campaigns/route.ts')
    expect(domain).toContain('WEDDING_SUPPORT')
    expect(domain).toContain('ITEM_EXPERIENCE')
    expect(ui).toContain('CONTRIBUTION_CAMPAIGN_TYPE_LABELS')
    expect(route).toContain('normalizeContributionCampaignType')
    expect(route).not.toContain("String(body.type ?? 'HONEYMOON')")
  })

  test('Admin financial Contributions are visible separately from legacy GuestContribution moderation', () => {
    const page = read('src/app/admin/contributions/page.tsx')
    const admin = read('src/components/admin/admin-financial-contributions.tsx')
    const nav = read('src/components/admin/admin-utility-nav.tsx')
    expect(page).toContain('SecureAdminFinancialContributions')
    expect(admin).toContain('separate from Guest Stories')
    expect(admin).toContain('summaryByCurrency')
    expect(nav).toContain('/admin/contributions')
  })

  test('Contribution fulfillment, verification and public campaign governance are audited', () => {
    const actions = read('src/app/api/planner/contributions/[id]/actions/route.ts')
    const campaigns = read('src/app/api/planner/contribution-campaigns/[id]/route.ts')
    expect(actions).toContain('contribution.fulfilled')
    expect(actions).toContain('contribution.verified')
    expect(actions).toContain("action === 'mark-verified'")
    expect(campaigns).toContain('contribution_campaign.updated')
    expect(campaigns).toContain('contribution_campaign.deleted_empty')
  })

  test('Executable Contributions browser gate proves create, persistence, campaign breadth and mobile reachability', () => {
    const browser = read('tests/e2e/planner-contributions.spec.ts')
    expect(browser).toContain('private contributor profile persists after reload')
    expect(browser).toContain("selectOption('HOME')")
    expect(browser).toContain('plannerPage.reload()')
    expect(browser).toContain('@mobile')
  })

  test('Campaign currency and contribution lifecycle input fail closed before database constraints', () => {
    const domain = read('src/lib/contributions.ts')
    const route = read('src/app/api/planner/contributions/route.ts')
    const detail = read('src/app/api/planner/contributions/[id]/route.ts')
    const campaign = read('src/app/api/planner/contribution-campaigns/[id]/route.ts')
    expect(domain).toContain('validContributionFulfillmentState')
    expect(route).toContain('CAMPAIGN_CURRENCY_MISMATCH')
    expect(detail).toContain('Contribution currency must match its campaign currency.')
    expect(campaign).toContain('Campaign currency cannot change after contributions are recorded.')
  })

  test('Planner contribution controls respect read versus edit permissions', () => {
    const route = read('src/app/api/planner/contributions/route.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(route).toContain("canEdit: contextHasPermission(access.context, 'budget.edit')")
    expect(route).toContain("canCreateTasks: contextHasPermission(access.context, 'planner.edit')")
    expect(ui).toContain('const canEdit = workspace?.permissions?.canEdit === true')
    expect(ui).toContain('disabled={saving || !canCreateTasks}')
  })

  test('Promised direct vendor support preserves its Budget target and fulfils through a real EngagementPayment', () => {
    const route = read('src/app/api/planner/contributions/route.ts')
    const actions = read('src/app/api/planner/contributions/[id]/actions/route.ts')
    const detail = read('src/app/api/planner/contributions/[id]/route.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(route).toContain("'DIRECT_PAYMENT'")
    expect(route).toContain('resolvedVendorId = engagement.vendorId')
    expect(actions).toContain("action === 'mark-direct-paid'")
    expect(actions).toContain('tx.engagementPayment.create')
    expect(actions).toContain('contribution.direct_vendor_paid')
    expect(actions).toContain('paidAmount: { increment: paymentAmount }')
    expect(actions).toContain("const nextFulfillment = complete ? 'PAID_DIRECT' : 'PARTIALLY_RECEIVED'")
    expect(actions).toContain('const remainingAfter = Math.max(0, promisedAmount - paidToDate)')
    expect(detail).toContain("allocation_kind <> 'DIRECT_PAYMENT'")
    expect(detail).toContain('Record the vendor payment through the direct-payment action')
    expect(ui).toContain('Record amount paid')
    expect(ui).toContain('To pay vendor directly')
    expect(ui).toContain('Part-paid vendor directly')
  })

  test('Campaign creation validates target amount and boolean governance fields', () => {
    const campaign = read('src/app/api/planner/contribution-campaigns/route.ts')
    expect(campaign).toContain('Target amount must be zero or more.')
    expect(campaign).toContain("['published','showTarget','showRaised','invitationVisible','showContributorRecognition']")
    expect(campaign).toContain('${targetAmount}, ${currency}')
  })

  test('Phase 2 exposes contributor/contribution edit and governed Vault evidence', () => {
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    const contributor = read('src/app/api/planner/contributors/[id]/route.ts')
    const evidence = read('src/app/api/planner/contributions/[id]/evidence/route.ts')
    expect(ui).toContain('Contributor profile')
    expect(ui).toContain('Contribution history')
    expect(ui).toContain('Evidence in Wewed Vault')
    expect(ui).toContain('Save details')
    expect(contributor).toContain("action:'contributor.updated'")
    expect(evidence).toContain('prepareVaultUpload')
    expect(evidence).toContain("entityType:'WeddingContribution'")
    expect(evidence).toContain("linkRole:'evidence'")
    expect(evidence).not.toContain('createBucket')
  })

  test('legacy paid facts are backfilled as replaceable unattributed funding without fabricated payments', () => {
    const migration = read('prisma/migrations/20260819190000_contributions_legacy_funding_backfill/migration.sql')
    const route = read('src/app/api/planner/budget/funding/route.ts')
    expect(migration).toContain("'LEGACY_UNATTRIBUTED'")
    expect(migration).toContain('Budget paidAmount existed without a durable payment/source record')
    expect(migration).not.toContain('INSERT INTO public."EngagementPayment"')
    expect(route).toContain("sourceKind !== 'LEGACY_UNATTRIBUTED'")
    expect(route).toContain("source_kind = 'LEGACY_UNATTRIBUTED'")
  })

  test('mixed funding is allocated against the real EngagementPayment instead of creating a second payment', () => {
    const paymentFunding = read('src/app/api/planner/payments/[id]/funding/route.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(paymentFunding).toContain('payment_id=${id}')
    expect(paymentFunding).toContain('FUNDING_EXCEEDS_PAYMENT')
    expect(paymentFunding).toContain('payment.funding_attributed')
    expect(paymentFunding).not.toContain('engagementPayment.create')
    expect(ui).toContain('Payment funding')
    expect(ui).toContain('Add funding split')
  })

  test('Phase 4 exposes contribution funding from Vendors and actionable lifecycle views', () => {
    const vendor = read('src/components/wedding/planner/modules/planner-vendors-module.tsx')
    const vendorApi = read('src/app/api/planner/vendors/funding-summary/route.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    const summary = read('src/app/api/planner/contributions/summary/route.ts')
    expect(vendor).toContain('Funding context')
    expect(vendorApi).toContain('sourceKind')
    expect(ui).toContain('value="overdue"')
    expect(ui).toContain('value="unverified"')
    expect(ui).toContain('Expected contribution date')
    expect(summary).toContain('expected_at < NOW()')
    expect(summary).toContain("verification_state = 'UNVERIFIED'")
  })

  test('Phase 5 campaign governance controls publication windows, canonical share paths, and double-gated recognition', () => {
    const patch = read('src/app/api/planner/contribution-campaigns/[id]/route.ts')
    const publicRoute = read('src/app/api/contribution-campaigns/public/route.ts')
    const share = read('src/app/api/planner/contribution-campaigns/share/route.ts')
    const ui = read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(patch).toContain('publish_from')
    expect(patch).toContain('show_contributor_recognition')
    expect(publicRoute).toContain('p.public_recognition=TRUE')
    expect(publicRoute).toContain('p.anonymous_public=FALSE')
    expect(share).toContain('/w/${encodeURIComponent(wedding.slug)}#registry')
    expect(ui).toContain('Prepare public gifting link / QR')
    expect(ui).toContain('Consented names:')
  })

  test('Phase 6 uses the existing worksheet engine and keeps AI drafting confirmation-only', () => {
    const types=read('src/lib/import-engine/types.ts')
    const schemas=read('src/lib/import-engine/schemas.ts')
    const contributionSchema=read('src/lib/import-engine/contribution-worksheet-schema.ts')
    const stage7=read('src/components/wedding/planner-workspace-stage7.tsx')
    const assist=read('src/app/api/planner/contributions/[id]/assist/route.ts')
    const ui=read('src/components/wedding/planner/planner-contributions-workspace.tsx')
    expect(types).toContain("| 'contributions'")
    expect(schemas).toContain('contributions: contributionWorksheetSchema')
    expect(contributionSchema).toContain('Direct vendor payments must be recorded through the governed Service Engagement/payment flow')
    expect(stage7).toContain("worksheetKey: 'contributions'")
    expect(assist).toContain('requiresUserConfirmation:true')
    expect(assist).toContain('financialMutationPerformed:false')
    expect(assist).not.toContain('plannerTask.create')
    expect(ui).toContain('Use as task title')
    expect(ui).toContain('Use as thank-you draft in Notebook')
  })

  test('direct vendor support cannot bypass Service Engagement or atomic payment fulfillment', () => {
    const create = read('src/app/api/planner/contributions/route.ts')
    const detail = read('src/app/api/planner/contributions/[id]/route.ts')
    const actions = read('src/app/api/planner/contributions/[id]/actions/route.ts')
    expect(create).toContain("if (directPayment && !serviceEngagementId)")
    expect(detail).toContain('Direct vendor fulfillment is controlled by the vendor-payment action')
    expect(detail).toContain('Direct vendor support must be created through the Service Engagement-aware direct-payment flow')
    expect(actions).toContain("action === 'mark-direct-paid'")
    expect(actions).toContain('engagementPayment.create')
  })

  test('optional contribution and campaign dates are validated before persistence', () => {
    const create = read('src/app/api/planner/contributions/route.ts')
    const campaign = read('src/app/api/planner/contribution-campaigns/route.ts')
    expect(create).toContain('INVALID_EXPECTED_DATE')
    expect(create).toContain('INVALID_PLEDGED_DATE')
    expect(create).toContain('INVALID_FULFILLED_DATE')
    expect(campaign).toContain('Publication end must be after its start.')
    expect(campaign).toContain("'showContributorRecognition'")
  })

  test('public recognition is double-consent and never exposes contributor contact or individual financial detail', () => {
    const publicRoute = read('src/app/api/contribution-campaigns/public/route.ts')
    expect(publicRoute).toContain('show_contributor_recognition')
    expect(publicRoute).toContain('p.public_recognition=TRUE')
    expect(publicRoute).toContain('p.anonymous_public=FALSE')
    expect(publicRoute).toContain('p.display_name')
    expect(publicRoute).not.toContain('p.email')
    expect(publicRoute).not.toContain('p.phone')
    expect(publicRoute).not.toContain('p.address')
    expect(publicRoute).toContain('invitation_visible')
    expect(publicRoute).not.toContain('contributorAmount')
  })
})
