import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const manager = readFileSync('src/components/wedding/invitation-manager.tsx', 'utf8')
const tools = readFileSync('src/components/wedding/planner-invitation-tools.tsx', 'utf8')
const page = readFileSync('src/app/planner/invitations/page.tsx', 'utf8')
const deliveryRoute = readFileSync('src/app/api/planner/guests/invitations/delivery/route.ts', 'utf8')
const projection = readFileSync('src/lib/planner-invitation-projection.ts', 'utf8')
const telemetry = readFileSync('src/lib/guest-invitation-telemetry.ts', 'utf8')
const plannerRoute = readFileSync('src/app/api/planner/guests/invitations/route.ts', 'utf8')
const guestSession = readFileSync('src/app/api/weddings/[slug]/guest-session/route.ts', 'utf8')
const premiumRsvp = readFileSync('src/components/wedding/invitation-experience/premium-invitation-rsvp-dialog.tsx', 'utf8')
const legacyRsvp = readFileSync('src/components/wedding/invitation-rsvp-dialog.tsx', 'utf8')
const androidRsvp = readFileSync('apps/android/app/src/main/java/pro/wewed/app/ui/invitation/LiveGuestInvitationScreen.kt', 'utf8')
const inviteRoute = readFileSync('src/app/invite/[slug]/route.ts', 'utf8')
const inviteContinue = readFileSync('src/app/invite/[slug]/continue/route.ts', 'utf8')
const pendingInvitation = readFileSync('src/lib/pending-invitation.ts', 'utf8')
const plannerTimeline = readFileSync('src/app/api/planner/timeline/route.ts', 'utf8')
const weddingDayGuest = readFileSync('src/app/api/wedding-day/guest/route.ts', 'utf8')

describe('Planner invitation command center', () => {
  test('has a durable planner route instead of a modal-only workspace', () => {
    expect(page).toContain('data-planner-invitations-page')
    expect(page).toContain('<PlannerInvitationTools embedded />')
    expect(page).toContain('<WeddingContextControls />')
    expect(tools).toContain('href="/planner/invitations"')
    expect(tools).not.toContain('<Dialog')
  })

  test('supports organizer-scale search, filters, selection and guest administration', () => {
    expect(manager).toContain('Invitation delivery command center')
    expect(manager).toContain('Search guest, email, phone, table, sender')
    expect(manager).toContain('All RSVP states')
    expect(manager).toContain('All delivery states')
    expect(manager).toContain('All open states')
    expect(manager).toContain('Select all')
    expect(manager).toContain('Mark selected sent')
    expect(manager).toContain('async function addGuest')
    expect(manager).toContain('async function saveGuest')
    expect(manager).toContain('async function deleteGuest')
    expect(manager).toContain('PAGE_SIZE = 40')
  })

  test('sent tracking is audit-only and cannot mutate RSVP or guest business state', () => {
    expect(deliveryRoute).toContain("action: 'guest.invitation_delivery_marked'")
    expect(deliveryRoute).toContain("action: 'guest.invitation_delivery_unmarked'")
    expect(deliveryRoute).toContain('db.auditEvent.createMany')
    expect(deliveryRoute).not.toContain('db.rSVP.update')
    expect(deliveryRoute).not.toContain('db.rSVP.create')
    expect(deliveryRoute).not.toContain('db.guest.update')
    expect(deliveryRoute).not.toContain('db.guest.delete')
  })

  test('actual invitation redemption is tracked separately without storing credentials', () => {
    expect(telemetry).toContain("action: 'guest.invitation_opened'")
    expect(telemetry).toContain("resourceType: 'guest_invitation'")
    expect(telemetry).not.toContain('rsvpToken')
    expect(telemetry).not.toContain('token:')
    expect(projection).toContain('openedAt')
    expect(projection).toContain("event.action === 'guest.invitation_opened'")
    expect(inviteContinue).toContain('recordGuestInvitationOpened')
    expect(inviteContinue).toContain('!pending.suppressOpenTracking')
    expect(inviteRoute).toContain("plannerPreview') === '1'")
    expect(pendingInvitation).toContain('suppressOpenTracking?: boolean')
    expect(manager).toContain("url.searchParams.set('plannerPreview', '1')")
  })

  test('planner programme and children policy converge into the guest wedding-day projection', () => {
    expect(plannerTimeline).toContain('db.programmeItem')
    expect(weddingDayGuest).toContain('FROM public."ProgrammeItem"')
    expect(weddingDayGuest).toContain('sortTimelineItems(programmeRows)')
    expect(weddingDayGuest).toContain('loadWeddingChildrenPolicy(context.weddingId)')
    expect(weddingDayGuest).toContain("childrenPolicy !== 'adults_only'")
  })

  test('planner message, deadline and children policy are canonical server-backed settings', () => {
    expect(plannerRoute).toContain('invitationCardMessage: message || null')
    expect(plannerRoute).toContain('rsvpDeadline')
    expect(plannerRoute).toContain("section: 'rsvp'")
    expect(plannerRoute).toContain("field: 'childrenPolicy'")
    expect(guestSession).toContain('const childrenPolicy = await loadWeddingChildrenPolicy(wedding.id)')
    expect(guestSession).toContain('invitationCardMessage: wedding.invitationCardMessage')
    expect(guestSession).toContain('rsvpDeadline: wedding.rsvpDeadline')
    expect(guestSession).toContain('childrenPolicy,')
    expect(premiumRsvp).toContain("data?.wedding.childrenPolicy === 'adults_only'")
    expect(legacyRsvp).toContain("data.wedding.childrenPolicy === 'adults_only'")
    expect(legacyRsvp).toContain('Children are not included in this RSVP')
    expect(androidRsvp).toContain('val adultsOnly = childrenPolicy == "adults_only"')
  })
})
