import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(path, 'utf8')

describe('targeted home, marketplace and provider iteration', () => {
  test('the documented scope authorizes only the six reviewed corrections', () => {
    const plan = source('docs/targeted-home-marketplace-vendor-iteration-2026-08-05.md')
    expect(plan).toContain('authorizes only the six corrections')
    expect(plan).toContain('It is not authorization for a general redesign')
    expect(plan).toContain('Cinematic homepage hero')
    expect(plan).toContain('Controlled marketplace fields')
    expect(plan).toContain('Honest Wedding Journey card')
    expect(plan).toContain('Live homepage account state')
    expect(plan).toContain('Interactive vendor and venue discovery')
    expect(plan).toContain('Task Test 11')
    expect(plan).toContain('Do not merge until the exact PR head')
  })

  test('the homepage keeps the Higgsfield wedding film and honest live journey state', () => {
    const home = source('src/components/public/public-platform-home-v2.tsx')
    expect(home).toContain('hf_20260804_140303_f8b02a87-f03b-4db5-81e2-969b5f3c3544.mp4')
    expect(home).toContain('<video')
    expect(home).toContain('muted')
    expect(home).toContain('autoPlay')
    expect(home).toContain('loop')
    expect(home).toContain('playsInline')
    expect(home).toContain("fetch('/api/auth/me'")
    expect(home).toContain('data-testid="wedding-journey-card"')
    expect(home).toContain('Example wedding journey · preview only')
    expect(home).not.toContain('Tariro & Tawanda')
    expect(home).not.toContain('Zimbabwe first')
    expect(home).not.toContain('designed for Africa')
  })

  test('the public shell resolves real dashboard and approved provider sessions', () => {
    const account = source('src/components/public/public-account-actions.tsx')
    const signOut = source('src/app/api/auth/sign-out/route.ts')
    expect(account).toContain("fetch('/api/auth/me'")
    expect(account).toContain("fetch('/api/providers/profile'")
    expect(account).toContain("role: 'provider'")
    expect(account).toContain("href: '/vendors/manage'")
    expect(account).toContain('No active account')
    expect(account).toContain("fetch('/api/auth/sign-out'")
    expect(signOut).toContain('clearAppSessionCookie')
    expect(signOut).toContain('supabase.auth.signOut()')
  })

  test('planner controlled classifications use checkbox groups without changing its profile API contract', () => {
    const form = source('src/components/marketplace/planner-marketplace-centre.tsx')
    const api = source('src/app/api/marketplace/profile/route.ts')
    for (const name of ['serviceAreas', 'services', 'weddingStyles', 'languages']) {
      expect(form).toContain(`name="${name}"`)
      expect(form).toContain(`data.getAll('${name}')`)
    }
    expect(form).toContain('function CheckboxGroup')
    expect(form).toContain('type="checkbox"')
    expect(form).toContain('defaultChecked={selected.includes(option)}')
    expect(form).toContain('Minimum guest count')
    expect(form).toContain('Maximum guest count')
    expect(form).toContain('Price band')
    expect(form).toContain('Availability')
    expect(api).toContain('stringList(body.serviceAreas, 30)')
    expect(api).toContain('stringList(body.services, 30)')
  })

  test('provider discovery uses normalized business profiles and never exposes wedding Vendor rows', () => {
    const directory = source('src/app/api/providers/route.ts')
    const profile = source('src/app/api/providers/profile/route.ts')
    const home = source('src/components/public/public-platform-home-v2.tsx')
    expect(directory).toContain('public."BusinessAccount"')
    expect(directory).toContain("type IN ('venue', 'vendor')")
    expect(directory).toContain('"onboardingStatus" = 'complete'')
    expect(directory).toContain('public."ProviderProfile"')
    expect(directory).toContain('public."ProviderServiceOffering"')
    expect(directory).toContain("WHERE p.visibility = 'published'")
    expect(directory).not.toContain('public."Vendor"')
    expect(profile).toContain('public."BusinessAccountMember"')
    expect(profile).toContain('public."ProviderProfile"')
    expect(profile).toContain('ProviderVerification')
    expect(profile).toContain('createServerClient')
    expect(home).toContain('/vendors?category=')
    expect(home).toContain('/vendors/manage')
  })

  test('provider registration preserves review flow with multi-service preselection', () => {
    const form = source('src/components/public/public-registration-form.tsx')
    const api = source('src/app/api/auth/register/route.ts')
    expect(form).toContain("searchParams.get('accountType')")
    expect(form).toContain("searchParams.get('service')")
    expect(form).toContain('Wedding services')
    expect(form).toContain('requestedServices')
    expect(form).toContain("requestedService: isProvider ? requestedServices[0] : null")
    expect(api).toContain('PROVIDER_CATEGORY_VALUES')
    expect(api).toContain('requestedServices')
    expect(api).toContain('requestedService')
    expect(api).toContain("'pending_review'")
    expect(api).toContain("'public_registration'")
  })
})
