import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { router } from 'expo-router'
import React, { useMemo, useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import { useSession } from '@/auth/session'
import { ActionButton, Body, Eyebrow, Field, Pill, Screen, Surface, Title } from '@/components/core'
import { WewedApiError, wewedRequest } from '@/lib/api'
import { colors, radius, spacing } from '@/theme/tokens'

type Participant={userId:string;name:string;email:string;role:string}
type Conversation={id:string;title:string|null;type:string;kind:string;status:string;unreadCount:number;lastMessageBody:string|null;lastMessageSenderName:string|null;lastVisibleMessageAt:string|null;participants:Participant[];relationshipBlocked?:boolean}
type Contact={id:string;name:string;email:string;role:string;defaultType:string;context:string;vendorProfileId?:string;vendorSlug?:string}

function conversationName(item:Conversation,currentUserId?:string){
  if(item.title?.trim())return item.title.trim()
  const other=item.participants?.filter(p=>p.userId!==currentUserId).map(p=>p.name).filter(Boolean)
  return other?.join(', ')||'Wewed conversation'
}

export default function MessagesScreen(){
  const {token,session}=useSession();const qc=useQueryClient();const key=['communications-conversations',session?.user.accessUserId]
  const [compose,setCompose]=useState(false);const [search,setSearch]=useState('');const [selected,setSelected]=useState<Contact|null>(null);const [initialMessage,setInitialMessage]=useState('');const [error,setError]=useState<string|null>(null)
  const conversations=useQuery({queryKey:key,enabled:Boolean(token),queryFn:()=>wewedRequest<{data:Conversation[]}>('/api/communications/conversations',{token}),refetchInterval:30_000})
  const contacts=useQuery({queryKey:['communications-contacts',session?.user.accessUserId],enabled:Boolean(token&&compose),queryFn:()=>wewedRequest<{data:Contact[]}>('/api/communications/contacts',{token})})
  const create=useMutation({mutationFn:()=>wewedRequest<{data:{id:string}}>('/api/communications/conversations',{token,method:'POST',body:JSON.stringify({participantIds:selected?[selected.id]:[],type:selected?.defaultType,title:null,weddingId:selected?.context==='wedding'?session?.activeWedding?.id:undefined,initialMessage:initialMessage.trim()||undefined})}),onSuccess:async(payload)=>{setCompose(false);setSelected(null);setInitialMessage('');setError(null);await qc.invalidateQueries({queryKey:key});router.push(`/messages/${payload.data.id}`)},onError:(cause)=>setError(cause instanceof WewedApiError?cause.message:'Conversation could not be started.')})
  const filteredContacts=useMemo(()=>{const q=search.trim().toLowerCase();return (contacts.data?.data??[]).filter(c=>!q||[c.name,c.email,c.role].some(v=>v.toLowerCase().includes(q)))},[contacts.data?.data,search])
  const unread=(conversations.data?.data??[]).reduce((sum,item)=>sum+Number(item.unreadCount||0),0)
  return <Screen>
    <View style={styles.header}><View style={styles.titleRow}><View style={styles.flexOne}><Eyebrow>Wewed Messages</Eyebrow><Title>Keep the wedding conversation inside the wedding.</Title></View>{unread>0?<Pill tone="clay">{unread} unread</Pill>:null}</View><Body muted>Couples, planners, vendors and Wewed support can work from one accountable communication history.</Body></View>
    <ActionButton label={compose?'Close new message':'New message'} variant={compose?'quiet':'primary'} onPress={()=>setCompose(v=>!v)}/>
    {compose?<Surface><Text style={styles.sectionTitle}>Start a conversation</Text><Field label="Find someone" value={search} onChangeText={setSearch} placeholder="Planner, vendor, couple or Wewed support"/>{contacts.isLoading?<Body muted>Loading people you can contact…</Body>:null}<View style={styles.contacts}>{filteredContacts.slice(0,20).map(contact=><Pressable key={contact.id} accessibilityRole="button" accessibilityState={{selected:selected?.id===contact.id}} onPress={()=>setSelected(contact)} style={({pressed})=>[styles.contact,selected?.id===contact.id&&styles.contactSelected,pressed&&{opacity:.65}]}><View style={styles.flexOne}><Text style={styles.contactName}>{contact.name}</Text><Text style={styles.meta}>{pretty(contact.role)} · {contact.context==='wedding'?'This wedding':'Wewed network'}</Text></View>{selected?.id===contact.id?<Text style={styles.check}>✓</Text>:null}</Pressable>)}</View>{selected?<><Field label={`Message ${selected.name}`} value={initialMessage} onChangeText={setInitialMessage} multiline placeholder="Write your first message…"/>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<ActionButton label="Start conversation" loading={create.isPending} onPress={async()=>{if(!initialMessage.trim()){setError('Write a message first.');return}create.mutate()}}/></>:null}</Surface>:null}
    <Surface><Text style={styles.sectionTitle}>Inbox</Text>{conversations.isLoading?<Body muted>Loading conversations…</Body>:null}{!conversations.isLoading&&(conversations.data?.data.length??0)===0?<Body muted>No conversations yet. Start one when you need to coordinate with someone.</Body>:null}{(conversations.data?.data??[]).map(item=><Pressable key={item.id} accessibilityRole="button" onPress={()=>router.push(`/messages/${item.id}`)} style={({pressed})=>[styles.conversation,pressed&&{opacity:.65}]}><View style={styles.avatar}><Text style={styles.avatarText}>{conversationName(item,session?.user.accessUserId).slice(0,1).toUpperCase()}</Text></View><View style={styles.flexOne}><View style={styles.convTitleRow}><Text numberOfLines={1} style={[styles.convTitle,item.unreadCount>0&&styles.unreadTitle]}>{conversationName(item,session?.user.accessUserId)}</Text>{item.unreadCount>0?<View style={styles.unreadDot}/>:null}</View><Text numberOfLines={2} style={[styles.preview,item.unreadCount>0&&styles.unreadPreview]}>{item.lastMessageSenderName?`${item.lastMessageSenderName}: `:''}{item.lastMessageBody||'Open conversation'}</Text><Text style={styles.meta}>{item.lastVisibleMessageAt?new Date(item.lastVisibleMessageAt).toLocaleString():pretty(item.type)}</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}</Surface>
  </Screen>
}
function pretty(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
const styles=StyleSheet.create({header:{gap:spacing.xs},titleRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm},sectionTitle:{color:colors.espresso,fontFamily:'serif',fontSize:22,fontWeight:'600'},contacts:{gap:spacing.xs},contact:{minHeight:58,flexDirection:'row',alignItems:'center',paddingHorizontal:spacing.sm,borderRadius:radius.md,borderWidth:1,borderColor:colors.border},contactSelected:{backgroundColor:colors.ivory,borderColor:colors.gold},contactName:{color:colors.espresso,fontSize:14,fontWeight:'800'},meta:{color:colors.inkMuted,fontSize:11,marginTop:2},check:{color:colors.sage,fontSize:20,fontWeight:'900'},conversation:{minHeight:76,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingVertical:spacing.sm,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border},avatar:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:colors.espresso},avatarText:{color:colors.goldLight,fontFamily:'serif',fontSize:20,fontWeight:'700'},convTitleRow:{flexDirection:'row',alignItems:'center',gap:spacing.xs},convTitle:{flex:1,color:colors.espresso,fontSize:15,fontWeight:'700'},unreadTitle:{fontWeight:'900'},preview:{color:colors.inkMuted,fontSize:12,lineHeight:17,marginTop:3},unreadPreview:{color:colors.espresso},unreadDot:{width:8,height:8,borderRadius:4,backgroundColor:colors.clay},arrow:{color:colors.goldMuted,fontSize:28},error:{color:colors.danger,fontSize:13},flexOne:{flex:1}})
