import { useMutation, useQuery } from '@tanstack/react-query'
import { router, Stack, useLocalSearchParams } from 'expo-router'
import React, { useState } from 'react'
import { Image, Linking, Pressable, Share, StyleSheet, Text, View } from 'react-native'
import { useSession } from '@/auth/session'
import { ActionButton, Body, Divider, Eyebrow, Field, Pill, Screen, Surface, Title } from '@/components/core'
import { WewedApiError, wewedRequest } from '@/lib/api'
import { colors, radius, spacing } from '@/theme/tokens'

type Offering={id:string;category:string;displayName:string;description:string|null;startingPriceCents:number|null;maximumPriceCents:number|null;currency:string;pricingModel:string|null;minimumCapacity:number|null;maximumCapacity:number|null;bookingLeadTime:string|null;serviceAreas:string[];inclusions:string[];packages:Array<{id:string;name:string;description:string|null;priceCents:number|null;currency:string;pricingUnit:string|null;inclusions:string[]}>}
type Provider={id:string;slug:string;displayName:string;headline:string|null;description:string|null;city:string|null;country:string|null;serviceAreas:string[];publicEmail:string|null;phone:string|null;website:string|null;yearsOperating:number|null;teamSize:number|null;responseTime:string|null;minimumBookingNotice:string|null;paymentMethods:string[];depositPolicy:string|null;cancellationPolicy:string|null;travelPolicy:string|null;culturalExperience:string|null;accessibilitySupport:string|null;coverImageUrl:string|null;verificationBadges:string[];listingStatus:string;isClaimable:boolean;acceptingEnquiries:boolean;claimNotice:string|null;offerings:Offering[]}

export default function ProviderScreen(){
  const {slug}=useLocalSearchParams<{slug:string}>();const {session,token}=useSession();const [offeringId,setOfferingId]=useState('');const [eventDate,setEventDate]=useState(session?.activeWedding?.date?.slice(0,10)??'');const [guestCount,setGuestCount]=useState('');const [location,setLocation]=useState(session?.activeWedding?.venueCity??'');const [budgetBand,setBudgetBand]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState<string|null>(null);const [sentConversation,setSentConversation]=useState<string|null>(null)
  const query=useQuery({queryKey:['provider',slug],enabled:Boolean(slug),queryFn:()=>wewedRequest<{provider:Provider}>(`/api/providers/${slug}`)})
  const provider=query.data?.provider;const selected=provider?.offerings.find(item=>item.id===offeringId)||provider?.offerings[0]
  const enquiry=useMutation({mutationFn:()=>wewedRequest<{conversationId:string}>('/api/providers/enquiries',{token,method:'POST',body:JSON.stringify({offeringId:selected?.id,eventDate:eventDate||undefined,guestCount:guestCount?Number(guestCount):undefined,location:location.trim()||undefined,budgetBand:budgetBand.trim()||undefined,message:message.trim()||undefined,sharedSummary:{weddingTitle:true,weddingDate:true,location:true,guestCount:true,budgetBand:Boolean(budgetBand.trim())}})}),onSuccess:payload=>{setSentConversation(payload.conversationId);setError(null)},onError:(cause)=>setError(cause instanceof WewedApiError?cause.message:'Enquiry could not be sent.')})
  if(query.isLoading)return <Screen><Body muted>Loading provider…</Body></Screen>
  if(!provider)return <Screen><Title>Provider unavailable</Title><Body muted>This Wewed profile could not be loaded.</Body></Screen>
  const approved=['verified','claimed'].includes(provider.listingStatus)||provider.verificationBadges.includes('Wewed Approved')
  return <Screen>
    <Stack.Screen options={{title:provider.displayName}}/>
    <View style={styles.hero}>{provider.coverImageUrl?<Image source={{uri:provider.coverImageUrl}} style={styles.cover}/>:<View style={[styles.cover,styles.fallback]}/>}<View style={styles.heroOverlay}/><View style={styles.heroText}><Eyebrow>{approved?'Wewed approved / owner-managed':'Provisional provider profile'}</Eyebrow><Text style={styles.heroTitle}>{provider.displayName}</Text><Text style={styles.heroMeta}>{[provider.city,provider.country].filter(Boolean).join(', ')}</Text></View></View>
    <View style={styles.actions}><ActionButton label="Share" variant="secondary" onPress={()=>Share.share({message:`${provider.displayName} on Wewed\nhttps://wewed.pro/vendors/${provider.slug}`})}/>{provider.phone?<ActionButton label="Call" variant="secondary" onPress={()=>Linking.openURL(`tel:${provider.phone}`)}/>:null}{provider.website?<ActionButton label="Website" variant="quiet" onPress={()=>Linking.openURL(provider.website!)}/>:null}</View>
    <Surface><View style={styles.titleRow}><View style={styles.flexOne}><Title>{provider.headline||provider.displayName}</Title></View><Pill tone={approved?'sage':'clay'}>{approved?'Approved':'Provisional'}</Pill></View>{provider.description?<Body>{provider.description}</Body>:null}{provider.claimNotice?<View style={styles.notice}><Text style={styles.noticeText}>{provider.claimNotice}</Text></View>:null}<Divider/><Fact label="Service areas" value={provider.serviceAreas.join(', ')||'Ask provider'}/><Fact label="Response" value={provider.responseTime||'Not stated'}/><Fact label="Operating" value={provider.yearsOperating?`${provider.yearsOperating} years`:'Not stated'}/><Fact label="Booking notice" value={provider.minimumBookingNotice||'Ask provider'}/>{provider.culturalExperience?<Fact label="Cultural experience" value={provider.culturalExperience}/>:null}</Surface>
    <Surface><Text style={styles.sectionTitle}>Services & packages</Text>{provider.offerings.map(offering=><Pressable key={offering.id} accessibilityRole="button" accessibilityState={{selected:selected?.id===offering.id}} onPress={()=>setOfferingId(offering.id)} style={[styles.offering,selected?.id===offering.id&&styles.offeringSelected]}><View style={styles.titleRow}><View style={styles.flexOne}><Text style={styles.offerTitle}>{offering.displayName}</Text><Text style={styles.meta}>{pretty(offering.category)}{offering.pricingModel?` · ${pretty(offering.pricingModel)}`:''}</Text></View>{offering.startingPriceCents!=null?<Text style={styles.price}>from {money(offering.startingPriceCents/100,offering.currency)}</Text>:null}</View>{offering.description?<Text style={styles.description}>{offering.description}</Text>:null}{offering.inclusions.length?<Text style={styles.meta}>Includes · {offering.inclusions.slice(0,5).join(' · ')}</Text>:null}{offering.packages.map(pack=><View key={pack.id} style={styles.package}><View style={styles.flexOne}><Text style={styles.packageName}>{pack.name}</Text>{pack.description?<Text style={styles.meta}>{pack.description}</Text>:null}</View>{pack.priceCents!=null?<Text style={styles.strong}>{money(pack.priceCents/100,pack.currency)}</Text>:null}</View>)}</Pressable>)}</Surface>
    {session?.user.role==='couple'&&provider.acceptingEnquiries&&approved&&selected?<Surface><Text style={styles.sectionTitle}>Ask {provider.displayName}</Text><Body muted>Your enquiry becomes a secure Wewed marketplace conversation. It does not create a booking or contract by itself.</Body><Field label="Wedding date" value={eventDate} onChangeText={setEventDate} placeholder="YYYY-MM-DD"/><Field label="Location" value={location} onChangeText={setLocation} placeholder="Harare"/><Field label="Guest count" value={guestCount} onChangeText={setGuestCount} keyboardType="number-pad" placeholder="Optional"/><Field label="Budget band" value={budgetBand} onChangeText={setBudgetBand} placeholder="Optional, e.g. USD 800–1,200"/><Field label="Message" value={message} onChangeText={setMessage} multiline placeholder="Tell the provider what you need…"/>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}{sentConversation?<><View style={styles.success}><Text style={styles.successText}>Enquiry sent securely through Wewed Messages.</Text></View><ActionButton label="Open conversation" onPress={()=>router.push(`/messages/${sentConversation}`)}/></>:<ActionButton label="Send secure enquiry" loading={enquiry.isPending} onPress={async()=>enquiry.mutate()}/>}</Surface>:null}
    {session?.user.role!=='couple'?<Surface><Text style={styles.sectionTitle}>Want to work with this provider?</Text><Body muted>Couple accounts can send governed marketplace enquiries. Planners can share this profile with the couple or add a known vendor from the Plan workspace.</Body></Surface>:null}
  </Screen>
}
function Fact({label,value}:{label:string;value:string}){return <View style={styles.fact}><Text style={styles.factLabel}>{label}</Text><Text style={styles.factValue}>{value}</Text></View>}
function pretty(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function money(v:number,c='USD'){try{return new Intl.NumberFormat('en',{style:'currency',currency:c,maximumFractionDigits:0}).format(v)}catch{return `${c} ${Math.round(v).toLocaleString()}`}}
const styles=StyleSheet.create({hero:{height:280,borderRadius:radius.lg,overflow:'hidden',backgroundColor:colors.espresso,justifyContent:'flex-end'},cover:{...StyleSheet.absoluteFillObject,width:'100%',height:'100%'},fallback:{backgroundColor:'#5B3428'},heroOverlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(26,20,16,.48)'},heroText:{padding:spacing.lg,gap:5},heroTitle:{fontFamily:'serif',fontSize:36,lineHeight:40,fontWeight:'600',color:colors.champagne},heroMeta:{color:'#E4D8CC',fontSize:13},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs},titleRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm},sectionTitle:{color:colors.espresso,fontFamily:'serif',fontSize:22,fontWeight:'600'},notice:{backgroundColor:'#FFF4EE',borderRadius:radius.md,padding:spacing.sm},noticeText:{color:colors.clay,fontSize:12,lineHeight:18,fontWeight:'600'},fact:{gap:2,paddingTop:spacing.xs},factLabel:{color:colors.goldMuted,fontSize:11,fontWeight:'900',textTransform:'uppercase',letterSpacing:1},factValue:{color:colors.espresso,fontSize:13,lineHeight:19},offering:{padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,gap:spacing.sm},offeringSelected:{borderColor:colors.gold,backgroundColor:colors.ivory},offerTitle:{color:colors.espresso,fontSize:17,fontWeight:'800'},meta:{color:colors.inkMuted,fontSize:11,lineHeight:16},price:{color:colors.goldMuted,fontSize:13,fontWeight:'900'},description:{color:colors.espresso,fontSize:13,lineHeight:19},package:{flexDirection:'row',gap:spacing.sm,padding:spacing.sm,borderRadius:radius.md,backgroundColor:colors.white},packageName:{color:colors.espresso,fontSize:13,fontWeight:'800'},strong:{color:colors.espresso,fontWeight:'900',fontSize:12},success:{backgroundColor:'#EEF4EC',borderRadius:radius.md,padding:spacing.sm},successText:{color:colors.success,fontSize:13,fontWeight:'800'},error:{color:colors.danger,fontSize:13},flexOne:{flex:1}})
