import SwiftUI

/// Autogenerated by mobile/contracts/generate_invitation_style_contract.py from src/lib/digital-invitation-card.ts.
/// Do not edit directly.

public struct InvitationPalette: Sendable, Equatable {
    public let stageHex: String
    public let paperHex: String
    public let inkHex: String
    public let primaryHex: String
    public let accentHex: String
    public let mutedHex: String

    public var stage: Color { Color(hex: stageHex) }
    public var paper: Color { Color(hex: paperHex) }
    public var ink: Color { Color(hex: inkHex) }
    public var primary: Color { Color(hex: primaryHex) }
    public var accent: Color { Color(hex: accentHex) }
    public var muted: Color { Color(hex: mutedHex) }

    public init(
        stageHex: String,
        paperHex: String,
        inkHex: String,
        primaryHex: String,
        accentHex: String,
        mutedHex: String
    ) {
        self.stageHex = stageHex
        self.paperHex = paperHex
        self.inkHex = inkHex
        self.primaryHex = primaryHex
        self.accentHex = accentHex
        self.mutedHex = mutedHex
    }
}

public enum InvitationMotion: String, Sendable, CaseIterable {
    case triFold = "tri-fold"
    case envelopeLetter = "envelope-letter"
    case gateFold = "gate-fold"
    case bookOpen = "book-open"
    case singleCardLift = "single-card-lift"
    case floralReveal = "floral-reveal"
    case sleevePull = "sleeve-pull"
}

public enum InvitationAtmosphere: String, Sendable, CaseIterable {
    case champagneGlow = "champagne-glow"
    case softBokeh = "soft-bokeh"
    case petals = "petals"
    case candlelight = "candlelight"
    case stars = "stars"
    case watercolourBloom = "watercolour-bloom"
    case minimal = "minimal"
}

public enum InvitationRendererKind: String, Sendable, CaseIterable {
    case ivoryCustom = "IVORY_CUSTOM"
    case genericMotion = "GENERIC_MOTION"
}

public struct InvitationThemeDefinition: Sendable {
    public let id: String
    public let name: String
    public let category: String
    public let motion: InvitationMotion
    public let atmosphere: InvitationAtmosphere
    public let palette: InvitationPalette
    public let rendererKind: InvitationRendererKind
}

public enum GeneratedInvitationStyles {
    public static let styles: [String: InvitationThemeDefinition] = [
        "ivory-floral-gold": InvitationThemeDefinition(
            id: "ivory-floral-gold",
            name: "Ivory Floral Gold",
            category: "classic",
            motion: .triFold,
            atmosphere: .champagneGlow,
            palette: InvitationPalette(stageHex: "#17130f", paperHex: "#fbf5e9", inkHex: "#42372f", primaryHex: "#b3833f", accentHex: "#d6b77c", mutedHex: "#7a6d62"),
            rendererKind: .ivoryCustom
        ),
        "midnight": InvitationThemeDefinition(
            id: "midnight",
            name: "Midnight Gold",
            category: "evening",
            motion: .gateFold,
            atmosphere: .stars,
            palette: InvitationPalette(stageHex: "#070b13", paperHex: "#101827", inkHex: "#fff8e8", primaryHex: "#d4af67", accentHex: "#f0d99b", mutedHex: "#b8bdc8"),
            rendererKind: .genericMotion
        ),
        "botanical": InvitationThemeDefinition(
            id: "botanical",
            name: "Garden Romance",
            category: "romantic",
            motion: .floralReveal,
            atmosphere: .petals,
            palette: InvitationPalette(stageHex: "#e9eadf", paperHex: "#fbf7ef", inkHex: "#2f392e", primaryHex: "#718167", accentHex: "#b99a62", mutedHex: "#6d7668"),
            rendererKind: .genericMotion
        ),
        "royal-emerald": InvitationThemeDefinition(
            id: "royal-emerald",
            name: "Royal Emerald",
            category: "classic",
            motion: .envelopeLetter,
            atmosphere: .softBokeh,
            palette: InvitationPalette(stageHex: "#071b16", paperHex: "#f8f1e3", inkHex: "#15382e", primaryHex: "#a98545", accentHex: "#d4bd88", mutedHex: "#668078"),
            rendererKind: .genericMotion
        ),
        "classic-white": InvitationThemeDefinition(
            id: "classic-white",
            name: "Classic White",
            category: "classic",
            motion: .bookOpen,
            atmosphere: .minimal,
            palette: InvitationPalette(stageHex: "#e8e5df", paperHex: "#fffdf9", inkHex: "#282521", primaryHex: "#8b806f", accentHex: "#c8bda9", mutedHex: "#77716a"),
            rendererKind: .genericMotion
        ),
        "blush-romance": InvitationThemeDefinition(
            id: "blush-romance",
            name: "Blush Romance",
            category: "romantic",
            motion: .envelopeLetter,
            atmosphere: .softBokeh,
            palette: InvitationPalette(stageHex: "#ead8d2", paperHex: "#fff7f1", inkHex: "#543b38", primaryHex: "#b68b79", accentHex: "#d8b992", mutedHex: "#8d716b"),
            rendererKind: .genericMotion
        ),
        "african-luxe": InvitationThemeDefinition(
            id: "african-luxe",
            name: "African Luxe",
            category: "cultural",
            motion: .gateFold,
            atmosphere: .candlelight,
            palette: InvitationPalette(stageHex: "#1b130e", paperHex: "#f5e9d3", inkHex: "#36251b", primaryHex: "#a76d2b", accentHex: "#d4a55b", mutedHex: "#786253"),
            rendererKind: .genericMotion
        ),
        "editorial": InvitationThemeDefinition(
            id: "editorial",
            name: "Modern Editorial",
            category: "modern",
            motion: .singleCardLift,
            atmosphere: .minimal,
            palette: InvitationPalette(stageHex: "#dedbd5", paperHex: "#f3efe7", inkHex: "#191714", primaryHex: "#191714", accentHex: "#9b8b72", mutedHex: "#706b65"),
            rendererKind: .genericMotion
        ),
        "black-tie": InvitationThemeDefinition(
            id: "black-tie",
            name: "Black Tie",
            category: "evening",
            motion: .gateFold,
            atmosphere: .candlelight,
            palette: InvitationPalette(stageHex: "#070707", paperHex: "#f8f3e8", inkHex: "#15120f", primaryHex: "#b89b68", accentHex: "#e2d1aa", mutedHex: "#736b61"),
            rendererKind: .genericMotion
        ),
        "watercolour-garden": InvitationThemeDefinition(
            id: "watercolour-garden",
            name: "Watercolour Garden",
            category: "romantic",
            motion: .floralReveal,
            atmosphere: .watercolourBloom,
            palette: InvitationPalette(stageHex: "#e7ebe4", paperHex: "#fffaf2", inkHex: "#344339", primaryHex: "#789178", accentHex: "#c58f83", mutedHex: "#708076"),
            rendererKind: .genericMotion
        ),
        "sunset-terracotta": InvitationThemeDefinition(
            id: "sunset-terracotta",
            name: "Sunset Terracotta",
            category: "modern",
            motion: .sleevePull,
            atmosphere: .softBokeh,
            palette: InvitationPalette(stageHex: "#3c2119", paperHex: "#fbebdc", inkHex: "#4a2b23", primaryHex: "#b76549", accentHex: "#d6a665", mutedHex: "#886d61"),
            rendererKind: .genericMotion
        ),
        "celestial": InvitationThemeDefinition(
            id: "celestial",
            name: "Celestial",
            category: "evening",
            motion: .bookOpen,
            atmosphere: .stars,
            palette: InvitationPalette(stageHex: "#050912", paperHex: "#101728", inkHex: "#f8f1df", primaryHex: "#c5a45f", accentHex: "#e0cf9c", mutedHex: "#abb3c5"),
            rendererKind: .genericMotion
        ),
    ]

    public static let fallbackStyleId = "botanical"
}
