import Foundation

/**
 * The digital invitation design a wedding is configured with.
 *
 * The invitation is a wedding-configured product object, not a native screen. Which design a guest
 * meets is the couple's saved choice — `wedding.invitationCardStyle` on the server — and native
 * must render THAT design, not an app-specific approximation of it.
 *
 * Every id here mirrors the web registry (`src/lib/digital-invitation-card.ts`) so one invitation
 * style has one identity across web and native. The list is generated by
 * `mobile/contracts/generate_invitation_style_contract.py` into
 * `mobile/contracts/invitation-styles.json`, which both platforms assert against.
 *
 * All 12 known styles have native renderers across Android Compose and iOS SwiftUI:
 * Ivory Floral Gold renders via its dedicated renderer, while the remaining 11 styles render
 * via the native generic premium motion engine. Truly unknown styles fail-closed.
 */
public enum InvitationStyle: String, CaseIterable, Sendable {
    case ivoryFloralGold = "ivory-floral-gold"
    case midnight = "midnight"
    case botanical = "botanical"
    case royalEmerald = "royal-emerald"
    case classicWhite = "classic-white"
    case blushRomance = "blush-romance"
    case africanLuxe = "african-luxe"
    case editorial = "editorial"
    case blackTie = "black-tie"
    case watercolourGarden = "watercolour-garden"
    case sunsetTerracotta = "sunset-terracotta"
    case celestial = "celestial"

    /// A style id the server sent that is not in the registry this build was compiled against.
    case unknownStyle = "unknown"

    public var wire: String { rawValue }

    public var displayName: String {
        switch self {
        case .ivoryFloralGold: return "Ivory Floral Gold"
        case .midnight: return "Midnight Gold"
        case .botanical: return "Garden Romance"
        case .royalEmerald: return "Royal Emerald"
        case .classicWhite: return "Classic White"
        case .blushRomance: return "Blush Romance"
        case .africanLuxe: return "African Luxe"
        case .editorial: return "Modern Editorial"
        case .blackTie: return "Black Tie"
        case .watercolourGarden: return "Watercolour Garden"
        case .sunsetTerracotta: return "Sunset Terracotta"
        case .celestial: return "Celestial"
        case .unknownStyle: return "This invitation design"
        }
    }

    public var themeDefinition: InvitationThemeDefinition? {
        GeneratedInvitationStyles.styles[wire]
    }

    /// Derived from the generated contract, never from enum membership alone: a style is only
    /// native-renderable if the generator actually classified it with a `rendererKind`. Adding a
    /// case here without regenerating the contract must NOT silently claim renderer support.
    public var hasNativeRenderer: Bool {
        rendererKind != nil
    }

    public var motion: InvitationMotion {
        themeDefinition?.motion ?? .triFold
    }

    public var atmosphere: InvitationAtmosphere {
        themeDefinition?.atmosphere ?? .minimal
    }

    public var palette: InvitationPalette {
        themeDefinition?.palette ?? GeneratedInvitationStyles.styles["botanical"]!.palette
    }

    public var rendererKind: InvitationRendererKind? {
        themeDefinition?.rendererKind
    }

    /// Mirrors the server's `normalizeInvitationCardStyle`: an absent or unrecognised value
    /// resolves to `botanical`, NOT to whichever style native happens to render.
    public static let `default`: InvitationStyle = .botanical

    public static func fromWire(_ value: String?) -> InvitationStyle {
        let normalised = (value ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased().replacingOccurrences(of: "_", with: "-")
        if normalised.isEmpty { return .default }
        return InvitationStyle(rawValue: normalised).flatMap { $0 == .unknownStyle ? nil : $0 }
            ?? .unknownStyle
    }
}

public enum ResolvedInvitationRenderer: Equatable, Sendable {
    case ivoryCustom
    case genericMotion
    case unsupported
}

public func rendererFor(_ style: InvitationStyle) -> ResolvedInvitationRenderer {
    switch style.rendererKind {
    case .ivoryCustom:
        return .ivoryCustom
    case .genericMotion:
        return .genericMotion
    case nil:
        return .unsupported
    }
}


/**
 * Where the invitation object is in its opening.
 *
 * Deliberately independent of RSVP state. The previous implementation let RSVP state decide WHICH
 * card to show — a confirmed guest was handed a different object entirely — which is how the
 * approved stationery came to be replaced by a summary card. These are orthogonal: a returning
 * confirmed guest is CLOSED + ATTENDING, and that is an ordinary, correct combination.
 */
public enum InvitationPresentationState: Sendable {
    /** Doors shut. The first frame a guest meets. Never skipped. */
    case closed

    /** The hinged reveal, ~1800ms, matching the web keyframes. */
    case opening

    /** The invitation face, with the couple, date, venue and the guest's personalisation. */
    case open

    /** The interactive details surface: RSVP, calendar, venue, gifts, a note. */
    case details
}

/// Everything the wedding has configured about its own invitation.
///
/// Resolved by the guest's slug in one read, because an invitation shown with some of its
/// configuration and defaults for the rest is not the invitation the couple made. Every field is
/// optional on purpose: absent means the couple did not set it, and the card must then not offer it
/// rather than inventing something plausible.
public struct WeddingInvitationConfiguration: Equatable, Sendable {
    /// `wedding.invitationCardStyle`.
    public let cardStyle: String?
    /// `wedding.monogram` — the couple's own, not initials this app derived.
    public let monogram: String?
    /// `wedding.tagline`.
    public let tagline: String?
    /// `wedding.invitationCardMessage` — the couple's note. Absent means there is no note.
    public let message: String?
    /// `wedding.rsvpDeadline`.
    public let rsvpDeadline: String?
    /// `wedding.venueMapUrl`, where the couple set one.
    public let venueMapUrl: String?
    /// `wedding.venueCountry`, for the location line.
    public let venueCountry: String?
    /// Where gift contributions go, when the wedding has that configured at all.
    public let giftDestinationUrl: String?
    public let provenance: DataProvenance

    public init(
        cardStyle: String?, monogram: String? = nil, tagline: String? = nil,
        message: String? = nil, rsvpDeadline: String? = nil, venueMapUrl: String? = nil,
        venueCountry: String? = nil, giftDestinationUrl: String? = nil,
        provenance: DataProvenance = .productionDerived
    ) {
        self.cardStyle = cardStyle
        self.monogram = monogram
        self.tagline = tagline
        self.message = message
        self.rsvpDeadline = rsvpDeadline
        self.venueMapUrl = venueMapUrl
        self.venueCountry = venueCountry
        self.giftDestinationUrl = giftDestinationUrl
        self.provenance = provenance
    }
}
