package pro.wewed.app.models

import androidx.compose.ui.graphics.Color

/**
 * Autogenerated by mobile/contracts/generate_invitation_style_contract.py from src/lib/digital-invitation-card.ts.
 * Do not edit directly.
 */

data class InvitationPalette(
    val stage: Color,
    val paper: Color,
    val ink: Color,
    val primary: Color,
    val accent: Color,
    val muted: Color,
    val stageHex: String,
    val paperHex: String,
    val inkHex: String,
    val primaryHex: String,
    val accentHex: String,
    val mutedHex: String
)

enum class InvitationMotion(val wire: String) {
    TRI_FOLD("tri-fold"),
    ENVELOPE_LETTER("envelope-letter"),
    GATE_FOLD("gate-fold"),
    BOOK_OPEN("book-open"),
    SINGLE_CARD_LIFT("single-card-lift"),
    FLORAL_REVEAL("floral-reveal"),
    SLEEVE_PULL("sleeve-pull");

    companion object {
        fun fromWire(wire: String?): InvitationMotion =
            entries.firstOrNull { it.wire == wire } ?: TRI_FOLD
    }
}

enum class InvitationAtmosphere(val wire: String) {
    CHAMPAGNE_GLOW("champagne-glow"),
    SOFT_BOKEH("soft-bokeh"),
    PETALS("petals"),
    CANDLELIGHT("candlelight"),
    STARS("stars"),
    WATERCOLOUR_BLOOM("watercolour-bloom"),
    MINIMAL("minimal");

    companion object {
        fun fromWire(wire: String?): InvitationAtmosphere =
            entries.firstOrNull { it.wire == wire } ?: MINIMAL
    }
}

enum class InvitationRendererKind {
    IVORY_CUSTOM,
    GENERIC_MOTION
}

data class InvitationThemeDefinition(
    val id: String,
    val name: String,
    val category: String,
    val motion: InvitationMotion,
    val atmosphere: InvitationAtmosphere,
    val palette: InvitationPalette,
    val rendererKind: InvitationRendererKind
)

object GeneratedInvitationStyles {
    fun parseColor(hex: String): Color {
        val clean = hex.removePrefix("#")
        val longVal = clean.toLong(16)
        return when (clean.length) {
            6 -> Color(0xFF000000 or longVal)
            8 -> Color(longVal)
            else -> Color.Black
        }
    }

    private fun palette(stage: String, paper: String, ink: String, primary: String, accent: String, muted: String): InvitationPalette =
        InvitationPalette(
            stage = parseColor(stage),
            paper = parseColor(paper),
            ink = parseColor(ink),
            primary = parseColor(primary),
            accent = parseColor(accent),
            muted = parseColor(muted),
            stageHex = stage,
            paperHex = paper,
            inkHex = ink,
            primaryHex = primary,
            accentHex = accent,
            mutedHex = muted
        )

    val STYLES: Map<String, InvitationThemeDefinition> = mapOf(
        "ivory-floral-gold" to InvitationThemeDefinition(
            id = "ivory-floral-gold",
            name = "Ivory Floral Gold",
            category = "classic",
            motion = InvitationMotion.TRI_FOLD,
            atmosphere = InvitationAtmosphere.CHAMPAGNE_GLOW,
            palette = palette("#17130f", "#fbf5e9", "#42372f", "#b3833f", "#d6b77c", "#7a6d62"),
            rendererKind = InvitationRendererKind.IVORY_CUSTOM
        ),
        "midnight" to InvitationThemeDefinition(
            id = "midnight",
            name = "Midnight Gold",
            category = "evening",
            motion = InvitationMotion.GATE_FOLD,
            atmosphere = InvitationAtmosphere.STARS,
            palette = palette("#070b13", "#101827", "#fff8e8", "#d4af67", "#f0d99b", "#b8bdc8"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "botanical" to InvitationThemeDefinition(
            id = "botanical",
            name = "Garden Romance",
            category = "romantic",
            motion = InvitationMotion.FLORAL_REVEAL,
            atmosphere = InvitationAtmosphere.PETALS,
            palette = palette("#e9eadf", "#fbf7ef", "#2f392e", "#718167", "#b99a62", "#6d7668"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "royal-emerald" to InvitationThemeDefinition(
            id = "royal-emerald",
            name = "Royal Emerald",
            category = "classic",
            motion = InvitationMotion.ENVELOPE_LETTER,
            atmosphere = InvitationAtmosphere.SOFT_BOKEH,
            palette = palette("#071b16", "#f8f1e3", "#15382e", "#a98545", "#d4bd88", "#668078"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "classic-white" to InvitationThemeDefinition(
            id = "classic-white",
            name = "Classic White",
            category = "classic",
            motion = InvitationMotion.BOOK_OPEN,
            atmosphere = InvitationAtmosphere.MINIMAL,
            palette = palette("#e8e5df", "#fffdf9", "#282521", "#8b806f", "#c8bda9", "#77716a"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "blush-romance" to InvitationThemeDefinition(
            id = "blush-romance",
            name = "Blush Romance",
            category = "romantic",
            motion = InvitationMotion.ENVELOPE_LETTER,
            atmosphere = InvitationAtmosphere.SOFT_BOKEH,
            palette = palette("#ead8d2", "#fff7f1", "#543b38", "#b68b79", "#d8b992", "#8d716b"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "african-luxe" to InvitationThemeDefinition(
            id = "african-luxe",
            name = "African Luxe",
            category = "cultural",
            motion = InvitationMotion.GATE_FOLD,
            atmosphere = InvitationAtmosphere.CANDLELIGHT,
            palette = palette("#1b130e", "#f5e9d3", "#36251b", "#a76d2b", "#d4a55b", "#786253"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "editorial" to InvitationThemeDefinition(
            id = "editorial",
            name = "Modern Editorial",
            category = "modern",
            motion = InvitationMotion.SINGLE_CARD_LIFT,
            atmosphere = InvitationAtmosphere.MINIMAL,
            palette = palette("#dedbd5", "#f3efe7", "#191714", "#191714", "#9b8b72", "#706b65"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "black-tie" to InvitationThemeDefinition(
            id = "black-tie",
            name = "Black Tie",
            category = "evening",
            motion = InvitationMotion.GATE_FOLD,
            atmosphere = InvitationAtmosphere.CANDLELIGHT,
            palette = palette("#070707", "#f8f3e8", "#15120f", "#b89b68", "#e2d1aa", "#736b61"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "watercolour-garden" to InvitationThemeDefinition(
            id = "watercolour-garden",
            name = "Watercolour Garden",
            category = "romantic",
            motion = InvitationMotion.FLORAL_REVEAL,
            atmosphere = InvitationAtmosphere.WATERCOLOUR_BLOOM,
            palette = palette("#e7ebe4", "#fffaf2", "#344339", "#789178", "#c58f83", "#708076"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "sunset-terracotta" to InvitationThemeDefinition(
            id = "sunset-terracotta",
            name = "Sunset Terracotta",
            category = "modern",
            motion = InvitationMotion.SLEEVE_PULL,
            atmosphere = InvitationAtmosphere.SOFT_BOKEH,
            palette = palette("#3c2119", "#fbebdc", "#4a2b23", "#b76549", "#d6a665", "#886d61"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
        "celestial" to InvitationThemeDefinition(
            id = "celestial",
            name = "Celestial",
            category = "evening",
            motion = InvitationMotion.BOOK_OPEN,
            atmosphere = InvitationAtmosphere.STARS,
            palette = palette("#050912", "#101728", "#f8f1df", "#c5a45f", "#e0cf9c", "#abb3c5"),
            rendererKind = InvitationRendererKind.GENERIC_MOTION
        ),
    )

    val FALLBACK_STYLE_ID: String = "botanical"
}
