package pro.wewed.app.models

/**
 * The digital invitation design a wedding is configured with.
 *
 * The invitation is a wedding-configured product object, not a native screen. Which design a guest
 * meets is the couple's saved choice — `wedding.invitationCardStyle` on the server — and native
 * must render THAT design, not an app-specific approximation of it.
 *
 * Every id here mirrors the web registry (`src/lib/digital-invitation-card.ts`) so one invitation
 * style has one identity across web and native. The list is generated by
 * `mobile/contracts/generate_invitation_style_contract.py` into
 * `mobile/contracts/invitation-styles.json`, which both platforms assert against.
 *
 * `nativeRenderer` is a claim that native reproduces THAT approved artwork. It is deliberately
 * true for exactly one style today. These designs differ in artwork, palette and motion — Garden
 * Romance is green with a floral bloom, Ivory Floral Gold is champagne with a tri-fold — so
 * treating one as a stand-in for another shows a couple's guests the wrong stationery.
 */
enum class InvitationStyle(
    val wire: String,
    val displayName: String,
    /** True only where native reproduces this exact approved design. */
    val hasNativeRenderer: Boolean
) {
    IVORY_FLORAL_GOLD("ivory-floral-gold", "Ivory Floral Gold", true),
    MIDNIGHT("midnight", "Midnight Gold", false),
    BOTANICAL("botanical", "Garden Romance", false),
    ROYAL_EMERALD("royal-emerald", "Royal Emerald", false),
    CLASSIC_WHITE("classic-white", "Classic White", false),
    BLUSH_ROMANCE("blush-romance", "Blush Romance", false),
    AFRICAN_LUXE("african-luxe", "African Luxe", false),
    EDITORIAL("editorial", "Modern Editorial", false),
    BLACK_TIE("black-tie", "Black Tie", false),
    WATERCOLOUR_GARDEN("watercolour-garden", "Watercolour Garden", false),
    SUNSET_TERRACOTTA("sunset-terracotta", "Sunset Terracotta", false),
    CELESTIAL("celestial", "Celestial", false),

    /** A style id the server sent that is not in the registry this build was compiled against. */
    UNKNOWN_STYLE("unknown", "This invitation design", false);

    companion object {
        /**
         * Mirrors the server's `normalizeInvitationCardStyle`: an absent or unrecognised
         * value resolves to `botanical`, NOT to whichever style native happens to render.
         */
        val DEFAULT: InvitationStyle = BOTANICAL

        fun fromWire(value: String?): InvitationStyle {
            val normalised = value?.trim()?.lowercase()?.replace('_', '-').orEmpty()
            if (normalised.isEmpty()) return DEFAULT
            return entries.firstOrNull { it.wire == normalised } ?: UNKNOWN_STYLE
        }
    }
}

/**
 * Where the invitation object is in its opening.
 *
 * Deliberately independent of RSVP state. The previous implementation let RSVP state decide WHICH
 * card to show — a confirmed guest was handed a different object entirely — which is how the
 * approved stationery came to be replaced by a summary card. These are orthogonal: a returning
 * confirmed guest is CLOSED + ATTENDING, and that is an ordinary, correct combination.
 */
enum class InvitationPresentationState {
    /** Doors shut. The first frame a guest meets. Never skipped. */
    CLOSED,

    /** The hinged reveal, ~1800ms, matching the web keyframes. */
    OPENING,

    /** The invitation face, with the couple, date, venue and the guest's personalisation. */
    OPEN,

    /** The interactive details surface: RSVP, calendar, venue, gifts, a note. */
    DETAILS
}

/**
 * Everything the wedding has configured about its own invitation.
 *
 * Resolved by the guest's slug in one read, because an invitation shown with some of its
 * configuration and defaults for the rest is not the invitation the couple made. Every field is
 * nullable on purpose: absent means the couple did not set it, and the card must then not offer it
 * rather than inventing something plausible.
 */
data class WeddingInvitationConfiguration(
    /** `wedding.invitationCardStyle`. */
    val cardStyle: String?,
    /** `wedding.monogram` — the couple's own, not initials this app derived. */
    val monogram: String?,
    /** `wedding.tagline`. */
    val tagline: String?,
    /** `wedding.invitationCardMessage` — the couple's note. Absent means there is no note. */
    val message: String?,
    /** `wedding.rsvpDeadline`. */
    val rsvpDeadline: String?,
    /** `wedding.venueMapUrl`, where the couple set one. */
    val venueMapUrl: String?,
    /** `wedding.venueCountry`, for the location line. */
    val venueCountry: String?,
    /** Where gift contributions go, when the wedding has that configured at all. */
    val giftDestinationUrl: String?,
    val provenance: DataProvenance = DataProvenance.PRODUCTION_DERIVED
)
