import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import React, { useState } from 'react'
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native'
import { useSession } from '@/auth/session'
import { ActionButton, Body, Eyebrow, Field, Pill, Screen, Surface, Title } from '@/components/core'
import { WewedApiError, wewedRequest } from '@/lib/api'
import { colors, spacing } from '@/theme/tokens'

type TimelineItem={id:string;time:string;title:string;notes:string;duration:string;location:string;order:number}

export default function TimelineScreen(){
  const {token,session}=useSession();const qc=useQueryClient();const key=['planner-timeline',session?.activeWedding?.id]
  const [time,setTime]=useState('');const [title,setTitle]=useState('');const [duration,setDuration]=useState('');const [location,setLocation]=useState('');const [notes,setNotes]=useState('');const [error,setError]=useState<string|null>(null)
  const query=useQuery({queryKey:key,enabled:Boolean(token&&session?.activeWedding),queryFn:()=>wewedRequest<{data:TimelineItem[]}>('/api/planner/timeline',{token})})
  const refresh=()=>qc.invalidateQueries({queryKey:key})
  const add=useMutation({mutationFn:()=>wewedRequest('/api/planner/timeline',{token,method:'POST',body:JSON.stringify({time:time.trim(),title:title.trim(),duration:duration.trim()||undefined,location:location.trim()||undefined,notes:notes.trim()||undefined})}),onSuccess:async()=>{setTime('');setTitle('');setDuration('');setLocation('');setNotes('');setError(null);await refresh()},onError:(cause)=>setError(cause instanceof WewedApiError?cause.message:'Timeline item could not be saved.')})
  const remove=useMutation({mutationFn:(id:string)=>wewedRequest(`/api/planner/timeline/${id}`,{token,method:'DELETE'}),onSuccess:refresh})
  return <Screen>
    <View style={styles.header}><Eyebrow>Plan · Timeline</Eyebrow><Title>Run the day, not a spreadsheet.</Title><Body muted>A compact event-day sequence designed to be readable while standing, walking and coordinating people.</Body></View>
    <Surface><Text style={styles.sectionTitle}>Add programme item</Text><View style={styles.row}><View style={styles.timeField}><Field label="Time" value={time} onChangeText={setTime} placeholder="14:30" keyboardType="numbers-and-punctuation"/></View><View style={styles.flexOne}><Field label="Event" value={title} onChangeText={setTitle} placeholder="Couple entrance"/></View></View><Field label="Location" value={location} onChangeText={setLocation} placeholder="Reception tent"/><Field label="Duration" value={duration} onChangeText={setDuration} placeholder="15 min"/><Field label="Notes" value={notes} onChangeText={setNotes} placeholder="MC cue, music, responsible person…" multiline/>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<ActionButton label="Add to timeline" loading={add.isPending} onPress={async()=>{if(!time.trim()){setError('Time is required.');return}if(!title.trim()){setError('Event title is required.');return}add.mutate()}}/></Surface>
    <Surface><View style={styles.titleRow}><View style={styles.flexOne}><Text style={styles.sectionTitle}>Wedding-day run</Text><Body muted>{query.data?.data.length??0} programme items</Body></View><Pill tone="gold">Chronological</Pill></View>{query.isLoading?<Body muted>Loading timeline…</Body>:null}{(query.data?.data??[]).map((item,index)=><View key={item.id} style={styles.item}><View style={styles.timelineRail}><View style={styles.dot}/>{index<(query.data?.data.length??0)-1?<View style={styles.line}/>:null}</View><View style={styles.flexOne}><Text style={styles.time}>{item.time}</Text><Text style={styles.itemTitle}>{item.title}</Text>{item.location?<Text style={styles.meta}>{item.location}</Text>:null}{item.duration?<Text style={styles.meta}>{item.duration}</Text>:null}{item.notes?<Text style={styles.notes}>{item.notes}</Text>:null}<Pressable accessibilityRole="button" onPress={()=>Alert.alert('Remove timeline item?',item.title,[{text:'Keep',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>remove.mutate(item.id)}])} style={styles.remove}><Text style={styles.removeText}>Remove</Text></Pressable></View></View>)}</Surface>
  </Screen>
}
const styles=StyleSheet.create({header:{gap:spacing.xs},sectionTitle:{color:colors.espresso,fontFamily:'serif',fontSize:22,fontWeight:'600'},row:{flexDirection:'row',gap:spacing.sm},timeField:{width:105},titleRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm},item:{flexDirection:'row',gap:spacing.sm,paddingTop:spacing.md,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border},timelineRail:{width:18,alignItems:'center'},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.gold,marginTop:7},line:{width:1,flex:1,minHeight:60,backgroundColor:colors.border,marginTop:4},time:{color:colors.goldMuted,fontSize:12,fontWeight:'900',letterSpacing:1},itemTitle:{color:colors.espresso,fontSize:17,fontWeight:'800',marginTop:2},meta:{color:colors.inkMuted,fontSize:12,marginTop:2},notes:{color:colors.espresso,fontSize:13,lineHeight:19,marginTop:5},remove:{minHeight:44,justifyContent:'center',alignSelf:'flex-start'},removeText:{color:colors.danger,fontSize:12,fontWeight:'800'},error:{color:colors.danger,fontSize:13},flexOne:{flex:1}})
