import { readFileSync } from 'node:fs'

function read(path: string) { return readFileSync(path, 'utf8') }
function requireText(source: string, needle: string, message: string) { if (!source.includes(needle)) throw new Error(message) }
function forbidText(source: string, needle: string, message: string) { if (source.includes(needle)) throw new Error(message) }

const plan = read('docs/WEWED_VENDOR_BOOKING_COMMERCE_AI_REFERRAL_PLAN.md')
const governance = read('src/lib/booking-governance.ts')
const resources = read('src/lib/booking-resource-engine.ts')
const commerce = read('src/lib/booking-commerce.ts')
const bookingAi = read('src/lib/booking-ai.ts')
const amendments = read('src/lib/booking-amendments.ts')
const publicForm = read('src/components/providers/provider-booking-form.tsx')
const lifecyclePanel = read('src/components/booking/booking-lifecycle-panel.tsx')
const vendorAvailability = read('src/app/vendor/availability/page.tsx')
const vendorCatalogPatch = read('src/app/api/vendor/catalog/[id]/route.ts')
const adminBookings = read('src/app/api/admin/bookings/route.ts')
const adminBookingsPage = read('src/app/admin/bookings/page.tsx')
const commercialMigration = read('prisma/migrations/20260824030900_booking_commercial_lifecycle_packages/migration.sql')
const historyMigration = read('prisma/migrations/20260824030500_booking_history_integrity/migration.sql')
const lineRevisionMigration = read('prisma/migrations/20260824031000_booking_line_revision_amendments/migration.sql')
const autoBookRaceMigration = read('prisma/migrations/20260824031100_autobook_budget_race_guard/migration.sql')
const concurrencyContract = read('scripts/booking-commerce-concurrency-contract.ts')
const postgresContract = read('scripts/booking-commerce-postgres-contract.sql')
const syntheticUat = read('scripts/booking-commerce-synthetic-uat.ts')

requireText(plan, 'WW-BOOKING-COMMERCE-2026-08-24-01', 'Booking implementation must remain tied to the stamped canonical plan.')
requireText(resources, 'pg_advisory_xact_lock', 'Transactional resource allocation must serialize competing reservations.')
requireText(resources, 'PACKAGE_COMPONENT_CYCLE', 'Package resource recursion must fail closed on cycles.')
requireText(resources, 'selectedAddOns', 'Resource engine must evaluate resource-consuming add-ons.')
requireText(resources, 'serviceLocation', 'Resource engine must evaluate service-area context.')
requireText(resources, 'serviceAreaPolicy', 'Resource engine must consume the canonical service-area policy column.')
requireText(resources, 'PAST_BOOKING_WINDOW', 'Deterministic availability must reject past booking windows even without a configured notice policy.')
requireText(governance, 'awaiting_deposit', 'Governed lifecycle must expose the deposit gate.')
requireText(governance, 'booking_deposit_is_satisfied', 'Application confirmation must verify canonical deposit evidence.')
requireText(governance, "false,'pending','unpaid'", 'Booking-created planner vendors must start unpaid; booking must never imply payment progress.')
forbidText(governance, "false,'pending','pending'", 'Booking-created planner vendors must not invent a pending payment state.')
requireText(commercialMigration, 'booking_deposit_not_satisfied', 'Database must independently block confirmation without deposit evidence.')
requireText(historyMigration, 'booking_events_are_append_only', 'Booking events must be append-only evidence.')
requireText(lineRevisionMigration, 'booking_line_commercial_snapshot_is_immutable', 'Submitted booking line snapshots must be immutable.')
requireText(autoBookRaceMigration, 'autobook-budget:', 'AutoBook budget authorization must serialize by wedding, not only by actor policy.')
requireText(autoBookRaceMigration, 'AutoBookBudgetReservation', 'AutoBook open commitments must have an auditable short-lived reservation boundary.')
requireText(bookingAi, 'reserve_autobook_open_budget', 'AI execution must reserve open-commitment authority atomically before creating a draft.')
requireText(bookingAi, 'AUTOBOOK_POLICY_CHANGED', 'AI execution must fail closed if authorization changes while an action is being prepared.')
requireText(amendments, 'contractAmendmentId', 'Booking amendments must converge with governed contract amendments when required.')
requireText(amendments, 'supersedesLineId', 'Accepted amendments must create booking-line revisions rather than overwrite history.')
requireText(publicForm, "params.set('location', location.trim())", 'Public Instant Book pre-check must send service location to the deterministic engine.')
requireText(publicForm, "params.set('addOns', selectedAddOns.join(','))", 'Public Instant Book pre-check must send selected resource add-ons to the deterministic engine.')
requireText(lifecyclePanel, '/deposit', 'My Bookings lifecycle UX must expose canonical deposit recheck.')
requireText(lifecyclePanel, '/amendments', 'My Bookings lifecycle UX must expose append-only amendments.')
requireText(vendorAvailability, '/availability-rules', 'Vendor UX must expose deterministic availability rules.')
requireText(vendorAvailability, '/components', 'Vendor UX must expose package/resource component configuration.')
requireText(vendorAvailability, 'operatingTimezone:', 'Vendor availability UX must persist the canonical operating timezone field.')
requireText(vendorAvailability, 'serviceAreaPolicy:', 'Vendor availability UX must persist the canonical structured service-area policy.')
requireText(vendorCatalogPatch, '"operatingTimezone"=CASE', 'Vendor catalogue mutation must persist the canonical operating timezone column.')
requireText(vendorCatalogPatch, '"serviceAreaPolicy"=CASE', 'Vendor catalogue mutation must persist the canonical service-area policy column.')
requireText(adminBookings, "requireWewedAdmin(request, 'admin.support.read')", 'Admin booking support must require governed support-read permission.')
requireText(adminBookingsPage, 'Read-only commercial support', 'Admin booking UI must remain support-oriented rather than a commercial bypass.')
requireText(concurrencyContract, 'Serialized gown concurrency', 'Dedicated contract must test serialized-item contention.')
requireText(concurrencyContract, 'Chair pool concurrency', 'Dedicated contract must test quantity-inventory contention.')
requireText(concurrencyContract, 'Package contract', 'Dedicated contract must test package component capacity.')
requireText(concurrencyContract, 'AutoBook concurrency contract', 'Dedicated contract must test concurrent AutoBook open-commitment contention.')
requireText(concurrencyContract, 'PAST_BOOKING_WINDOW', 'Dedicated contract must prove past booking windows fail closed.')
requireText(syntheticUat, 'Synthetic gown', 'Synthetic UAT must exercise a gown archetype without claiming Shandy facts.')
requireText(syntheticUat, 'Synthetic chairs', 'Synthetic UAT must exercise quantity rental without claiming Shandy facts.')
requireText(postgresContract, 'booking_deposit_not_satisfied', 'PostgreSQL contract must prove database deposit enforcement.')

forbidText(commerce, 'export async function holdBooking(', 'Legacy hold mutation must not remain exported from booking-commerce.')
forbidText(commerce, 'export async function submitBooking(', 'Legacy submit mutation must not remain exported from booking-commerce.')
forbidText(commerce, 'export async function providerBookingAction(', 'Legacy provider state mutation must not remain exported from booking-commerce.')

console.log('Booking commerce source contract: PASS')
